title: <p align="center"> Harjaspreet Singh </p>
logo: /assets/img/logo.png

description:
  <p align="center">
    
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handling the Big Data from real-time Ad call data.
  
  <br>
  </p>



theme: jekyll-theme-minimal
